site_name: "FFT-Analysator"
site_description: "Eine Dokumentation für den FFT-Analysator"
site_url: "https://kalleculated.github.io/FFT-Analysator/"
repo_url: "https://github.com/Kalleculated/FFT-Analysator/"
repo_name: "FFT-Analysator/FFT-Analysator"
watch: [mkdocs.yml, docs, src/fft_analysator]
site_dir: "site"

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
- Home:
  - Overview: index.md
- Getting Started:
  - Installation: installation.md
- User Documentation:
  - Main functions: user_documentation.md
  - Screenshots and Examples: screenshots_and_examples.md
- Developer Documentation:
  - Backend Documentation: dev_backend_documentation.md
  - Frontend Documentation: dev_frontend_documentation.md

theme:
  name: material
  logo: logo.png
  custom_dir: docs/.overrides
  features:
  - announce.dismiss
  #- content.action.edit
  #- content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.indexes
  # - navigation.sections
  # - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to system preference


plugins:
- search
- markdown-exec
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        - https://mkdocstrings.github.io/autorefs/objects.inv
        - https://www.mkdocs.org/objects.inv
        - https://python-markdown.github.io/objects.inv
        paths: [src]
        options:
          docstring_options:
            ignore_init_summary: true
          docstring_section_style: table
          filters: ["!^_"]
          heading_level: 1
          inherited_members: true
          merge_init_into_class: true
          parameter_headings: true
          separate_signature: true
          show_root_heading: true
          show_root_full_path: false
          show_signature_annotations: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          signature_crossrefs: true
          summary: true

markdown_extensions:
  - pymdownx.superfences
