name: Deploy MkDocs Site

on:
  push:
    branches:
      - main  # Der Branch, auf dem die Änderungen vorgenommen werden
  workflow_dispatch:  # Ermöglicht das manuelle Auslösen des Workflows

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Stelle sicher, dass dies eine mit MkDocs kompatible Python-Version ist

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocstrings mkdocstrings-python markdown-exec pymdown-extensions

      - name: Build MkDocs Site
        run: mkdocs build  # Hier wird mkdocs.yml im Root verwendet

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site  # Der Standard-Publish-Ordner von MkDocs
